MagSciASPNetDemo.Web/Controllers/EventsController.cs
using ContactsManagement.Core.Domain.Entities.ContactsManager;
using ContactsManagement.Core.Domain.IdentityEntities;
using ContactsManagement.Core.DTO.CompaniesManagement;
using ContactsManagement.Core.DTO.EventsManager;
using ContactsManagement.Core.Enums.ContactsManager;
using ContactsManagement.Core.ServiceContracts.AccountManager;
using ContactsManagement.Core.ServiceContracts.EventsManager;
using ContactsManagement.Core.Services.EventsManager;
using ContactsManagement.Web.Filters.ExceptionFilters;
using ContactsManagement.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ContactsManagement.Web.Controllers
{
    [Route("[controller]")]
    [TypeFilter(typeof(RedirectToIndexExceptionFilter))]
    public class EventsController : Controller
    {
        private readonly IEventsAdderService _eventsAdderService;
        private readonly IEventsGetterService _eventsGetterService;
        private readonly IEventsUpdaterService _eventsUpdaterService;
        private readonly IEventsDeleterService _eventsDeleterService;
        public EventsController(IEventsAdderService eventsAdderService, IEventsGetterService eventsGetterService, IEventsUpdaterService eventsUpdaterService, IEventsDeleterService eventsDeleterService) 
        {
            _eventsAdderService = eventsAdderService;
            _eventsGetterService = eventsGetterService;
            _eventsUpdaterService = eventsUpdaterService;
            _eventsDeleterService = eventsDeleterService;
        }
        [Route("[action]")]
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(List<string>? errors = null, bool isActiveEvent = true)
        {

            List<EventResponse>? events = new List<EventResponse>();
            if (isActiveEvent)
            {
                events = await _eventsGetterService.GetFilteredEvents(statusType: StatusType.Active);
                ViewBag.IsActiveEvents = true;
            }
            else
            {
                events = await _eventsGetterService.GetFilteredEvents(statusType: StatusType.Completed);
                ViewBag.IsActiveEvents = false;
            }
            return View(events);
        }
        [Route("[action]")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Route("[action]")]
        [HttpPost]
        public async Task<IActionResult> Create(EventAddRequest eventAddRequest) 
        {
            if (ModelState.IsValid)
            {
                _ = await _eventsAdderService.AddEvent(eventAddRequest);
                ViewBag.Success = "Event has been added";
                return View();
            }
            else
            {
                ViewBag.Errors = ModelState.Values.SelectMany(V => V.Errors).Select(err => err.ErrorMessage).ToList();
                return View(eventAddRequest);
            }
        }
        [Route("[action]")]            // How bout don't make a mistake? :^)
        [HttpGet]
        public async Task<IActionResult> Edit(int eventId)
        {
            EventResponse? @event = await _eventsGetterService.GetEventById(eventId);
            if (@event == null)
            {
                return StatusCode(404);
            }
            EventUpdateRequest eventUpdateRequest = @event.ToEventUpdateRequest();
            return View(eventUpdateRequest);
        }
        [Route("[action]")]
        [HttpPost]
        public async Task<IActionResult> Edit(EventUpdateRequest eventUpdateRequest)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Errors = ModelState.Values.SelectMany(V => V.Errors).Select(err => err.ErrorMessage).ToList();
                return View(eventUpdateRequest);
            }
            bool isUpdated = await _eventsUpdaterService.UpdateEvent(eventUpdateRequest);
            if (isUpdated)
            {
                return RedirectToAction("Index");
            } else {
                ViewBag.Errors = new List<string>() { "Error: Something went wrong. Please try again later"};
                return View(eventUpdateRequest);
            }
        }
        [Route("[action]")]
        [HttpDelete]
        public async Task<IActionResult> Delete([FromQuery] int eventId)
        {
            bool isDeleted = await _eventsDeleterService.DeleteEvent(eventId);
            return isDeleted ? StatusCode(200) : StatusCode(500);
        }
        [Route("[action]")]
        [HttpPost]
        public async Task<IActionResult> EventCompleted([FromQuery] int eventId)
        {
            bool isUpdated = await _eventsUpdaterService.UpdateEventCompletion(eventId);
            return isUpdated ? StatusCode(200) : StatusCode(500);
        }
    }
}

MagSciASPNetDemo.Web/Controllers/PersonsController.cs
using ContactsManagement.Core.ServiceContracts.ContactsManager.PersonsServices;
using ContactsManagement.Core.DTO.ContactsManager;
using ContactsManagement.Core.Enums.ContactsManager;
using ContactsManagement.Core.ServiceContracts.ContactsManager;
using ContactsManagement.Web.Filters.ActionFilters;
using ContactsManagement.Web.Filters.AlwaysRunResultFilter;
using ContactsManagement.Web.Filters.AuthorizationFilter;
using ContactsManagement.Web.Filters.ExceptionFilters;
using ContactsManagement.Web.Filters.FactoryFilters;
using ContactsManagement.Web.Filters.ResourceFilters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using ContactsManagement.Core.ServiceContracts.CompaniesManagement;
using ContactsManagement.Core.ServiceContracts.Others.V2;
using MediaStorageServices.Interfaces.v1;

namespace ContactsManagement.Web.Controllers
{
    [Route("persons")]
    [TypeFilter(typeof(AlwaysRunResultFilter))]
    [ResponseHeaderActionFilter("Controller-Key", "In-PersonsController",3)]
    [TypeFilter(typeof(RedirectToIndexExceptionFilter))]
    public class PersonsController : Controller
    {
        private readonly IPersonsGetterService _personGetterService;
        private readonly IPersonsAdderService _personAdderService;
        private readonly IPersonsDeleterService _personsDeleterService;
        private readonly IPersonsGroupIdFilteredGetterService _personsGroupIdFilteredGetterService;
        private readonly IPersonsSorterService _personsSorterService;
        private readonly IPersonsUpdaterService _personsUpdaterService;
        private readonly ICountriesService _countriesService;
        private readonly ICompanyAdderByNameService _companyAdderByNameService;
        private readonly IImageUploadService _imageUploaderService;
        private readonly IImageDeleterService _imageDeleterService;

        public PersonsController(IPersonsGetterService personsGetterService, IPersonsAdderService personsAdderService, IPersonsDeleterService personsDeleterService, IPersonsSorterService personsSorterService, IPersonsUpdaterService personsUpdaterService, IPersonsGroupIdFilteredGetterService personsGroupIdFilteredGetterService, ICountriesService countriesService, IImageUploadService imageUploadService, IImageDeleterService imageDeleterService, ICompanyAdderByNameService companyAdderByNameService)
        {
            _personGetterService = personsGetterService;
            _personAdderService = personsAdderService;
            _personsSorterService = personsSorterService;
            _personsUpdaterService = personsUpdaterService;
            _personsDeleterService = personsDeleterService;
            _personsGroupIdFilteredGetterService = personsGroupIdFilteredGetterService;
            _countriesService = countriesService;
            _companyAdderByNameService = companyAdderByNameService;
            _imageUploaderService = imageUploadService;
            _imageDeleterService = imageDeleterService;
        }        
        [Route("[action]")]
        [AllowAnonymous]
        [TypeFilter(typeof(PersonsListActionFilter))]
        [ResponseHeaderActionFilter("Action-Key", "In-Index-Method", 1)]        
        public async Task<IActionResult> Index(string? searchProperty, string? searchString, int? groupId, string? displayType, string sortProperty = "Name", string sortOrder = "ASC", List<string>? errors = null)
        {
            ViewBag.Errors = errors;
            List<PersonResponse>? personList = new List<PersonResponse>() { };
            if(groupId != null)
            {
                personList = await _personsGroupIdFilteredGetterService.GetFilteredPersons(groupId, searchProperty, searchString);
            } else
            {
                personList = await _personGetterService.GetFilteredPersons(searchProperty, searchString);
            }
            
            //Sorting
            switch (sortOrder)
            {
                case "ASC":
                    personList = await _personsSorterService.GetSortedPersons(personList, sortProperty, SortOrderOptions.ASC);
                    break;
                case "DESC":
                    personList = await _personsSorterService.GetSortedPersons(personList, sortProperty, SortOrderOptions.DESC);
                    break;
            }
            return View(personList);
        }
        [HttpGet]
        [Route("create")]
        [TypeFilter(typeof(PersonCreateAndEditActionFilter))]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [Route("create")]
        [TypeFilter(typeof(PersonCreateAndEditActionFilter))]
        public async Task<IActionResult> Create([FromForm] PersonAddRequest? personAddRequest,[FromForm] IFormFile? profileImage)
        {
            if (profileImage != null && profileImage.Length > 0 && profileImage.ContentType.StartsWith("image/"))
            {
                try
                {
                    personAddRequest.ProfileBlobUrl = await _imageUploaderService.UploadAsync(profileImage);
                }
                catch
                {
                    ViewBag.Error = new List<string>() { "An error occured while uploading the image." };
                }                
            }

            if (personAddRequest.CompanyName != null)
                personAddRequest.CompanyId = await _companyAdderByNameService.AddCompanyByName(personAddRequest.CompanyName);
            try
            {
                _ = await _personAdderService.AddPerson(personAddRequest);
                ViewBag.Success = "Person has been successfully added!";
            }
            catch
            {
                //Delete Image if exception occurs during transaction
                if(personAddRequest.ProfileBlobUrl != null)
                    await _imageDeleterService.DeleteAsync(personAddRequest.ProfileBlobUrl);
            }
            return View(new PersonAddRequest() { });
        }
        [HttpPost]
        [Route("[action]/{personId}")]
        [TypeFilter(typeof(PersonCreateAndEditActionFilter))]     
        public async Task<IActionResult> Edit([FromForm] PersonUpdateRequest personUpdateRequest,[FromForm] IFormFile? profileImage)
        {
            if (profileImage != null && profileImage.Length > 0 && profileImage.ContentType.StartsWith("image/"))
            {
                if (personUpdateRequest.ProfileBlobUrl != null)
                    await _imageDeleterService.DeleteAsync(personUpdateRequest.ProfileBlobUrl);

                try
                {
                    personUpdateRequest.ProfileBlobUrl = await _imageUploaderService.UploadAsync(profileImage);
                }
                catch
                {
                    personUpdateRequest.ProfileBlobUrl = null;
                    ViewBag.Error = new List<string>() { "An error occured while uploading the image." };
                }      
            }
                
            PersonResponse? personResponse = await _personsUpdaterService.UpdatePerson(personUpdateRequest);              
            PersonUpdateRequest personUpdated = personResponse.ToPersonUpdateRequest();
            ViewBag.Success = "Person has been successfully updated!";
            return View(personUpdated);            
        }
        [HttpGet]
        [Route("[action]/{personId}")]
        [TypeFilter(typeof(PersonCreateAndEditActionFilter))]        
        [TypeFilter(typeof(HandleExceptionFilter))]
        public async Task<IActionResult> Edit(Guid? personId, List<string>? errors = null)
        {
            PersonResponse? matchingPerson = await _personGetterService.GetPersonById(personId);
            if (matchingPerson == null)
                return RedirectToAction("Index");

            ViewBag.Errors = errors;
            ViewBag.Countries = await LoadCountrySelectItems();
            PersonUpdateRequest personToUpdate = matchingPerson.ToPersonUpdateRequest();
            return View(personToUpdate);
        }
        [HttpDelete]
        [Route("[action]")]
        public async Task<IActionResult> Delete(Guid personId)
        {
            bool isPersonDeleted = false;
            
            PersonResponse? person = await _personGetterService.GetPersonById(personId);
            if (person.ProfileBlobUrl != null)
            {
                bool isImageDeleted = false;
                isImageDeleted = await _imageDeleterService.DeleteAsync(person.ProfileBlobUrl);

                if (isImageDeleted)
                    isPersonDeleted = await _personsDeleterService.DeletePerson(personId);
            }
            else
            {
                isPersonDeleted = await _personsDeleterService.DeletePerson(personId);
            }
            
            
            if (isPersonDeleted)
            {
                return StatusCode(200);
            }
            else
            {
                return StatusCode(500);
            }
        }
        [Route("[action]")]
        public async Task<IActionResult> PersonsPDF()
        {
            List<PersonResponse> allPersons = await _personGetterService.GetAllPersons();
            if (allPersons.IsNullOrEmpty())
                return RedirectToAction("Index", new { errors = "Table is empty" });

            //Rotativa
            return new ViewAsPdf("PersonsPDF", allPersons, ViewData)
            {
                PageMargins = new Margins()
                {
                    Top = 20,
                    Right = 20,
                    Left = 20,
                    Bottom = 20
                },
                PageOrientation = Orientation.Landscape
            };
        }        
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> PersonsCSV()
        {

MagSciASPNetDemo.Web/Views/Shared/Partials/_AutoScriptsPartial.cshtml
@*
<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlert.js" asp-append-version="true"></script>*@
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var closeButton = document.querySelector("#status_card_section .btn-close");
        var alertElement = document.querySelector("#status_card_section .alert");

        closeButton.addEventListener("click", function () {
            alertElement.classList.add("d-none");
        });
    });
</script>

MagSciASPNetDemo.Web/Views/Shared/Partials/_ErrorCardPartial.cshtml
@{
    List<string>? Errors = ViewBag.Errors;
}
@if (Errors != null && Errors.Count > 0)
{
<section class="mb-3" id="error_card_section">
    <div class="card card-body border-danger" >    
        <ul class="text-danger">
            @foreach (string error in Errors)
            {
                <li class="text-danger">@error</li>
            }
        </ul>
    </div>
    <input type="hidden" id="_ErrorCardFlag" name="_ErrorCardFlag" value="true"/>
</section>
}
else
{
<input type="hidden" id="_ErrorCardFlag" name="_ErrorCardFlag" value="false"/>
}    

MagSciASPNetDemo.Web/Views/Shared/Partials/_InfoCardPartial.cshtml
@{
    string? infoMessage = ViewBag.Info;
    if (!User.Identity.IsAuthenticated)
    {
        infoMessage = "You are currently using a demo version.";
    }

}
@if (infoMessage != null)
{
    <section class="mb-3" id="status_card_section">
        <div class="alert alert-info alert-dismissible fade show">
            @infoMessage
            <button type="button" class="btn-close" aria-label="Close"></button>
        </div>
    </section>
}

MagSciASPNetDemo.Web/Views/Shared/Partials/_NavbarPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- Left elements -->
        <div class="d-flex">
            <!-- Brand -->
            <a asp-controller="Home" asp-action="Index" class="navbar-brand" style="font-family: 'Roboto Mono', monospace;
                    font-weight: bold;
                    color:#124265;
                    font-size: 24px;">Contacts Management
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-around" id="navbarNav">
        <!-- Center elements -->
        <ul class="navbar-nav flex-row d-flex">
            <li class="nav-item me-3 me-lg-1">
                <a asp-controller="Persons" asp-action="Index" class="nav-link">
                    <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="Contacts"><i class="fa-solid fa-address-book fa-lg"></i></span>
                    @*<span><i class="fas fa-users fa-lg"></i></span>*@
                </a>
            </li>
            <li class="nav-item me-3 me-lg-1">
                <a asp-controller="Events" asp-action="Index" class="nav-link">
                    <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="Events"><i class="fa-solid fa-calendar-check fa-lg"></i></span>
                    @*<span class="badge rounded-pill badge-notification bg-danger">2</span>*@
                </a>
            </li>
            <li class="nav-item me-3 me-lg-1">
                <a asp-controller="Companies" asp-action="Index" class="nav-link">
                    <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="Companies"><i class="fa-solid fa-building fa-lg"></i></span>
                </a>
            </li>
            <li class="nav-item me-3 me-lg-1">
                <a asp-controller="ContactLogs" asp-action="Index" class="nav-link">
                    <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logs"><i class="fa-solid fa-book fa-lg"></i></span>
                </a>
            </li>            
        </ul>
        <!-- Right elements -->
        <ul class="navbar-nav flex-row d-flex">            
            <li class="nav-item dropdown me-3 me-lg-1">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" aria-expanded="false">
                    Download Data
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="nav-link" asp-controller="Persons" asp-action="PersonsPDF"><i class="fa-solid fa-file-pdf"></i> PDF</a></li>
                    <li><a class="nav-link" asp-controller="Persons" asp-action="PersonsCSV"><i class="fa-solid fa-file-csv"></i> CSV</a></li>
                    <li><a class="nav-link" asp-controller="Persons" asp-action="PersonsExcel"><i class="fa-solid fa-table"></i> EXCEL</a></li>
                </ul>
            </li>           
            <partial name="_AuthenticationPartial"></partial>
        </ul>
        <!-- Right elements -->        
        </div>
    </div>
</nav>
<!-- Navbar -->

MagSciASPNetDemo.Web/Views/Shared/Partials/_SuccessCardPartial.cshtml
@if(ViewBag.Success != null)
{
    <section class="row">
        <div class="card card-body border-success">
            <p class="text-success">@ViewBag.Success</p>
        </div>
    </section>   
}